mongodb:
  primary:
    host: localhost
    port: 27017
    database: first
  secondary:
    host: localhost
    port: 27017
    database: second

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  thymeleaf:
    cache: false
  template:
    cache: false
  data:
    mongodb:
      port: 0